import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.CellBiologyHedgehogSignalingTheoremCanonicalLaneLean.SignalingPathwayComponents
import HautevilleHouse.CellBiologyHedgehogSignalingTheoremCanonicalLaneLean.TranscriptionFactorActivation
import HautevilleHouse.CellBiologyHedgehogSignalingTheoremCanonicalLaneLean.CiliumTransportMechanism
import HautevilleHouse.CellBiologyHedgehogSignalingTheoremCanonicalLaneLean.NegativeRegulationPathway
import HautevilleHouse.CellBiologyHedgehogSignalingTheoremCanonicalLaneLean.SignalingGradientMorphogenesis

namespace HautevilleHouse
namespace CellBiologyHedgehogSignalingTheoremCanonicalLaneLean

def ConstrainedHedgehogClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_hedgehog_endgame (A : AdmissibleClass) :
    ConstrainedHedgehogClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end CellBiologyHedgehogSignalingTheoremCanonicalLaneLean
end HautevilleHouse